vm:
  base:
    version: "generic/alpine317"
    provider: "virtualbox"
    cpu: 2
    ram: 2048
    hostname: "gmadecS"
    bridge: eth1
  network:
    ip: "192.168.42.110"
    port_guest: 80
    port_host: 8080
  provision:
    shell: "install.sh"

