vagrantbox: generic/alpine317
provider: virtualbox
network: 192.168.42
machines:
  server:
    hostname: dzondaS
    network: private_network
    ip: 192.168.42.110
    cpu: 2
    ram: 2048
    provision:
      files:
        app:
          src: "src"
          out: "/home/vagrant/app"
        # manifests:
        #   src: "manifests"
        #   out: "/home/vagrant/manifests"
      shell:
        k3s:
          path: "./scripts/provision-server.sh"
