# Vagrant Config

VM_BOX = "centos/stream8" #"centos/8" 
VM_BOX_VERSION = "20210210.0"
BOX_URL = "https://app.vagrantup.com/centos/boxes/8/versions/2011.0/providers/virtualbox.box"
VM_PROVIDER = "virtualbox"
VM_NETWORK = "private_network"
VM_CPUS = "1"
VM_MEMORY = "512"

# Machines Config

SERVER_NAME = "dzondaS"
SERVER_IP = "192.168.56.100"

# K3S Config

K3S_CHANNEL = 'latest'
K3S_VERSION = 'v1.21.10+k3s1'

Vagrant.configure("2") do |config|
  # config.vagrant.plugins = "vagrant-vbguest"

  config.vm.box = VM_BOX
  config.vm.box_check_update = true
	# config.vbguest.installer_options = { allow_kernel_upgrade: true }

  # config.vm.box_version = VM_BOX_VERSION
  # config.vm.box = "centos/stream8"
  # config.vm.box_version = "20210210.0"

  config.vm.provider VM_PROVIDER do |vb|
    vb.cpus = VM_CPUS
    vb.memory = VM_MEMORY
  end

  config.vm.provision "file", source: "~/.ssh/id_vagrant.pub", destination: "/tmp/id_rsa.pub"
  config.vm.provision "file", source: "~/.ssh/id_vagrant", destination: "/tmp/id_rsa"
  config.vm.provision "shell", path: "./scripts/provision-base.sh"

  config.vm.define SERVER_NAME do |s|
    s.vm.hostname = SERVER_NAME
    s.vm.network VM_NETWORK, ip: SERVER_IP
    s.vm.provider VM_PROVIDER do |vmp|
      vmp.name = SERVER_NAME
    end

    s.vm.synced_folder "./srcs", "/home/vagrant", type: 'virtualbox'
    s.vm.provision "shell", path: "./scripts/provision-server.sh"
  end
end
