# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

options = YAML.load_file('config.yml')

Vagrant.configure("2") do |config|
  machines = options.fetch('machines')
  machines.each do |name, machine|
    config.vm.define "#{name}" do |instance|
      instance.vm.box = options.fetch('vagrantbox')
      instance.vm.hostname = machine.fetch('hostname')
      instance.vm.network machine.fetch('network'), ip: machine.fetch('ip')

      instance.vm.provider options.fetch('provider') do |provider|
        provider.name = machine.fetch('hostname')
        provider.cpus = machine.fetch('cpu')
        provider.memory = machine.fetch('ram')
      end

      files = machine.fetch('provision').fetch('files')
      files.each do |_, file|
        instance.vm.provision "file", source: "#{file['src']}", destination: "#{file['out']}"
      end

      scripts = machine.fetch('provision').fetch('shell')
      scripts.each do |_, script|
        instance.vm.provision "shell", path: "#{script['path']}"
      end

      instance.vm.synced_folder "./manifests", "/home/vagrant/manifests", type: "virtualbox"
    end
  end
end
