# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'
options = YAML.load_file('config.yml')

Vagrant.configure("2") do |config|
  vm = options.fetch("vm")
  base = vm.fetch("base")
  network = vm.fetch("network")
  provision = vm.fetch("provision")

  # Setup base of the vm
  config.vm.define base.fetch("hostname")
  config.vm.box = base.fetch("version")
  config.vm.hostname = base.fetch("hostname")
  config.vm.provider base.fetch("provider") do |vm_virtualbox|
    vm_virtualbox.gui = false
    vm_virtualbox.name = base.fetch("hostname")
    vm_virtualbox.memory = base.fetch("ram")
    vm_virtualbox.cpus = base.fetch("cpu")
  end

  # Network
  config.vm.network "private_network", bridge: machine.fetch('bridge'), ip: network.fetch("ip")

  # Setup
  config.vm.provision "file", source: "k3s_cluster", destination: "/home/vagrant/k3s_cluster"
  config.vm.provision "shell", path: provision.fetch("shell")

end
