apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.10.1
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: "Hello from app2."

---
apiVersion: v1
kind: Service
metadata:
  name: app2
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: app2

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app2
spec:
  rules:
  - host: app2.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: app2
            port:
              number: 8080
