vagrantbox: generic/alpine317
provider: virtualbox
shared:
  network: 192.168.56.
  cpu: 1
  ram: 1024
server:
  hostname: dzondaS
  network: private_network
  ip: 192.168.56.110
  cpu: 2
  ram: 1024
agent:
  hostname: dzondaSW 
  network: private_network
  ip: 192.168.56.111
  cpu: 2
  ram: 1024
