default:
  vagrantbox: generic/alpine317
  provider: virtualbox
  provision:
    auth:
      src: "auth"
      out: "/home/vagrant/auth"
machines:
  server:
    provider: virtualbox
    hostname: dzondaS
    network: private_network
    ip: 192.168.42.110
    cpu: 2
    ram: 1024
    provision:
      files:
        auth:
          src: "auth"
          out: "/home/vagrant/auth"
      shell:
        base:
          path: "./scripts/provision-base.sh"
        server:
          path: "./scripts/provision-server.sh"
  worker:
    provider: virtualbox
    hostname: dzondaSW 
    network: private_network
    ip: 192.168.42.111
    cpu: 2
    ram: 1024
    provision:
      files:
        auth:
          src: "auth"
          out: "/home/vagrant/auth"
      shell:
        base:
          path: "./scripts/provision-base.sh"
        server:
          path: "./scripts/provision-worker.sh"
