vagrantbox: generic/alpine317
vmguest: :alpine
provider: virtualbox
network: 192.168.56
server:
  hostname: dzondaS
  cpu: 1
  ram: 1024
  ip: 192.168.56.110
  network: private_network
agent:
  hostname: dzondaSW 
  cpu: 1
  ram: 1024
  ip: 192.168.56.111
  network: private_network
