machines:
  dzondaS:
    vagrantbox: generic/alpine317
    provider: virtualbox
    hostname: dzondaS
    network: private_network
    bridge: eth1
    ip: 192.168.42.110
    cpu: 2
    ram: 1024
    gui: false
    provision:
      files:
        ssh:
          src: "ssh"
          out: "/home/vagrant/ssh"
        utils:
          src: "../utils"
          out: "/home/vagrant/utils"
      shell:
        base:
          path: "./scripts/provision-base.sh"
        server:
          path: "./scripts/provision-server.sh"
  dzondaSW:
    vagrantbox: generic/alpine317
    provider: virtualbox
    hostname: dzondaSW 
    network: private_network
    bridge: eth1
    ip: 192.168.42.111
    cpu: 2
    ram: 1024
    gui: false
    provision:
      files:
        ssh:
          src: "ssh"
          out: "/home/vagrant/ssh"
        utils:
          src: "../utils"
          out: "/home/vagrant/utils"
      shell:
        base:
          path: "./scripts/provision-base.sh"
        server:
          path: "./scripts/provision-worker.sh"
