default:
  vagrantbox: generic/ubuntu2204
  provider: virtualbox
  # network: 192.168.56
machines:
  server:
    hostname: dzondaS
    cpu: 2
    ram: 2048
    # ip: 192.168.42.110
    network: bridge
